- title: Strategy & Transformation
  description: >
    Co-create analytics operating models, prioritize high-impact initiatives, and stand up
    governance that keeps data programs aligned with executive goals.
  deliverables:
    - Operating model blueprints
    - Prioritized roadmaps with ROI guardrails
    - Change management playbooks
- title: Managed Analytics Delivery
  description: >
    Embed product-minded data scientists, engineers, and PMs who build, launch, and maintain
    decision tools that teams rely on every day.
  deliverables:
    - Cross-functional delivery pods
    - Automated reporting and alerting
    - Ongoing reliability and adoption monitoring
- title: AI Acceleration Labs
  description: >
    Rapidly prototype, validate, and scale AI and LLM use cases from whiteboard concepts to
    production-ready workflows with stakeholder-ready artifacts.
  deliverables:
    - Use-case discovery workshops
    - Pilot-to-production playbooks
    - Adoption and risk dashboards
