- title: The 'Year of Agents' Narrative
  description: >
    While AI agents show promise, current systems remain brittle and limited in scope. 
    True autonomous agents require robust error handling, reliable long-term memory, 
    and the ability to recover from failures—capabilities we're still developing.
  deliverables:
    - Most "agents" are still glorified API wrappers
    - Real autonomy requires self-correction and planning
    - We're still in the "demo works, production fails" phase
- title: The Infrastructure Gap
  description: >
    The fundamental challenge isn't model capability—it's the surrounding infrastructure. 
    Agents need reliable tool use, consistent outputs, proper evaluation frameworks, 
    and systems that degrade gracefully when they inevitably make mistakes.
  deliverables:
    - Current LLMs lack persistent memory and context
    - Tool use remains fragile and error-prone
    - We need better evaluation beyond benchmarks
- title: AGI Timeline Reality Check
  description: >
    Despite rapid progress, AGI remains at least a decade away. We're getting better at 
    narrow tasks, but general intelligence requires breakthroughs in reasoning, long-term 
    planning, and the ability to learn from experience like humans do.
  deliverables:
    - Scaling laws are slowing down
    - We're optimizing for benchmarks, not intelligence
    - True understanding vs. pattern matching gap remains
